Repository genomic-medicine-sweden/tomte, pull requests merged in 2024-10, with the labels that each got.

#147 Adds possibility to make drop database
  .nf-core.yml
  CHANGELOG.md
  bin/drop_config.py
  bin/drop_sample_annot.py
  conf/base.config
  docs/usage.md
  modules/local/drop_config_runAE.nf
  modules/local/drop_config_runAS.nf
  modules/local/drop_filter_results.nf
  modules/local/drop_sample_annot.nf
  nextflow.config
  nextflow_schema.json
  subworkflows/local/analyse_transcripts.nf
  test_data/vep_to_download.csv
  test_data/vep_to_download_37.csv
  workflows/tomte.nf
Labels: Ready for review

#167 Template update for nf-core/tools version 3.0.2
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/download_pipeline.yml
  .github/workflows/linting.yml
  .github/workflows/linting_comment.yml
  .github/workflows/release-announcements.yml
  .github/workflows/template_version_comment.yml
  .gitignore
  .gitpod.yml
  .nf-core.yml
  .pre-commit-config.yaml
  CHANGELOG.md
  CITATIONS.md
  README.md
  assets/schema_input.json
  assets/vep_plugin_files_schema.json
  conf/base.config
  conf/igenomes_ignored.config
  conf/test.config
  docs/images/mqc_fastqc_adapter.png
  docs/images/mqc_fastqc_counts.png
  docs/images/mqc_fastqc_quality.png
  docs/usage.md
  main.nf
  modules.json
  modules/nf-core/fastqc/environment.yml
  modules/nf-core/fastqc/meta.yml
  modules/nf-core/multiqc/environment.yml
  modules/nf-core/multiqc/main.nf
  modules/nf-core/multiqc/meta.yml
  modules/nf-core/multiqc/tests/main.nf.test
  modules/nf-core/multiqc/tests/main.nf.test.snap
  modules/nf-core/multiqc/tests/nextflow.config
  nextflow.config
  nextflow_schema.json
  subworkflows/local/utils_nfcore_tomte_pipeline/main.nf
  subworkflows/nf-core/utils_nextflow_pipeline/main.nf
  subworkflows/nf-core/utils_nextflow_pipeline/tests/nextflow.config
  subworkflows/nf-core/utils_nfcore_pipeline/main.nf
  subworkflows/nf-core/utils_nfschema_plugin/main.nf
  subworkflows/nf-core/utils_nfschema_plugin/meta.yml
  subworkflows/nf-core/utils_nfschema_plugin/tests/main.nf.test
  subworkflows/nf-core/utils_nfschema_plugin/tests/nextflow.config
  subworkflows/nf-core/utils_nfschema_plugin/tests/nextflow_schema.json
  subworkflows/nf-core/utils_nfvalidation_plugin/main.nf
  subworkflows/nf-core/utils_nfvalidation_plugin/meta.yml
  subworkflows/nf-core/utils_nfvalidation_plugin/tests/main.nf.test
  subworkflows/nf-core/utils_nfvalidation_plugin/tests/tags.yml
  workflows/tomte.nf
Labels: Ready for review

#169 add parameter --skip_variant_calling
  .github/workflows/ci.yml
  .nf-core.yml
  CHANGELOG.md
  conf/modules/call_variants.config
  docs/images/tomte_pipeline_metromap.eps
  docs/images/tomte_pipeline_metromap.png
  docs/images/tomte_pipeline_metromap.svg
  docs/usage.md
  nextflow.config
  nextflow_schema.json
Labels: enhancement, Ready for review

#172 make module_to_export_counts_folder
  CHANGELOG.md
  bin/drop_sample_annot_exported_counts.py
  conf/modules/analyse_transcripts.config
  modules/local/drop_config_runAE.nf
  modules/local/drop_config_runAS.nf
  modules/local/drop_put_together_exported_couts.nf
  subworkflows/local/analyse_transcripts.nf
Labels: Ready for review

#174 Fix versions in multiqc and ymls for drop modules
  CHANGELOG.md
  README.md
  bin/drop_config.py
  bin/drop_filter_results.py
  bin/drop_sample_annot.py
  modules/local/drop_config_runAE.nf
  modules/local/drop_config_runAS.nf
  modules/local/drop_filter_results.nf
  modules/local/drop_sample_annot.nf
Labels: bug

#168 Sex info to DROP
  .gitignore
  CHANGELOG.md
  assets/schema_input.json
  bin/drop_sample_annot.py
  modules/local/drop_sample_annot.nf
  nextflow_schema.json
  subworkflows/local/analyse_transcripts.nf
Labels: enhancement, Ready for review
